Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -16,6 +16,9 @@ jobs:
   build:
 
     runs-on: ubuntu-latest
+    
+    permissions:
+      checks: write
 
     steps:
     - uses: actions/checkout@v4
@@ -26,6 +29,7 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
+        pip install numpy>=1.21.0,<1.24.0 pandas==1.5.3
         pip install flake8 pytest
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - name: Lint with flake8
@@ -38,3 +42,11 @@ jobs:
     - name: Test with pytest    
       run: |
         python -m pytest --verbose --junit-xml=junit.xml
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+           report_paths: '**/junit.xml'
+           detailed_summary: true
+           include_passed: true
